version: '3.7'

services:
  app:
    image: dreadlabs/php-lib:7.3-dev
    command: ["php", "-S", "0.0.0.0:8000", "-t", "apps/resilience-talk/public/"]
    ports:
      - 8000:8000
    volumes:
      - .:/app
    working_dir: "/app"

  redis:
    image: redis:5.0

  http-echo:
    image: mendhak/http-https-echo
